tx-gas-limit = "45000000"
disable-access-list-simulation = true

[[solver]]
name = "baseline" # Arbitrary name given to this solver, must be unique
endpoint = "http://baseline"
absolute-slippage = "40000000000000000" # Denominated in wei, optional
relative-slippage = "0.1" # Percentage in the [0, 1] range
account = "" # solver 3 private key

[submission]
gas-price-cap = "1000000000000"

[[submission.mempool]]
mempool = "public"

[liquidity]
base-tokens = [
    "0xADcb2f358Eae6492F61A5F87eb8893d09391d160", # WETH
    "0x24ac48bf01fd6CB1C3836D08b3EdC70a9C4380cA", # USDC
]

[[liquidity.uniswap-v2]] # Custom Uniswap V2 configuration
router = "0x85aA63EB2ab9BaAA74eAd7e7f82A571d74901853"
pool-code = "0x89e28f0672d230e32003ce2233112a4f044ab0238d476078999b58524fa386db"
missing-pool-cache-time = "1h"

# [[liquidity.uniswap-v3]] # Uniswap V3 configuration
# router = "0xD81F56576B1FF2f3Ef18e9Cc71Adaa42516fD990"
# max-pools-to-initialize = 100 # how many of the deepest pools to initialise on startup
# max-pools-per-tick-query = 9223372036854775807
# graph-url = "https://api.goldsky.com/api/public/project_cm97l77ib0cz601wlgi9wb0ec/subgraphs/v3-subgraph/6.0.0/gn" # which subgraph url to fetch the data from
# reinit-interval = "12h"